name: Testes

run-name: ${{ github.actor }} fez commit no projeto

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Versão do GitHub Actions
      - uses: actions/checkout@v4

      - name: Configurando o Python
        # Versão do action para o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          architecture: 'x64'

      - name: Instalando dependências
        run: pip install -r requirements.txt

      - name: Rodando os testes
        run: python -m pytest